- name: Expense Backend setup
  hosts: all
  become: yes
  tasks:
    - name: Disable NodeJS default version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: Enable NodeJs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: istall NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: copy Backend Service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add Application User
      ansible.builtin.user:
        name: expense
    - name: delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create App Directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: Download nodejs Dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: Install mysql clients
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: load schema
      ansible.builtin.shell: mysql -h mysql-dev.pdeveops965.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enbled: yes
        daemon-reload: yes
        
        
